[package]
name = "wavetable_resampler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

hound = "3.5.0"
plugin_util = { git = "https://github.com/AquaEBM/plugin_util.git"}